sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: school
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  rabbitmq:
    host: 192.168.200.135
    port: 5672
    username: user
    password: user
