sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: school
    username: root
    password: 123456

  rabbitmq:
    host: 192.168.200.141
    port: 5672
    username: user
    password: user